services:
  - type: web
    name: webcafe
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn webcafe.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: webcafe.settings
      - key: PYTHON_VERSION
        value: "3.11"
